name: gigadetector
dependencies:
 - python=3.7
 - anaconda::tensorflow-gpu=1
 - conda-forge::opencv=4.1
 - conda-forge::matplotlib
 - requests
 - pillow
 - scikit-learn
 - scikit-image
 - gdown
 - lxml
 - cython
 - imgaug
